### ISSUE TITLE
AUDIOSOCKET SERVER OPERATION DOUBTS

### ISSUE THREAD

**Issue by c13nt189** [NormHarrison/audiosocket_server#2]
Dear NormHarrison, initially I wanted to congratulate you for the contribution you make to the VoIP and Asterisk communities with your AudioSocket Server project in Python, I inform you that I am using your project to explore a use case in which I need to extract the streams from audio of a live call to use it with google transcription services (STT) and obtain the text of what is spoken on that particular channel.

I want to ask if you see possible that I can achieve this objective using your project with Asterisk 18 using AudioSocket () as an application in the dial plan, additionally you see possible to obtain some example of how to integrate audio streams as input to STT transcription services external like google or others available.

I've been trying, but I almost always get messages associated with the audio socket server queue “'[AUDIOSOCKET WARNING] The inbound audio queue is full! This most ' + \ 'likely occurred because the read() method is not being called, skipping frame”, I have not yet been able to make transcripts, I appreciate any contribution that you consider can guide or guide me to achieve my goal, greetings !.

**Comment by NormHarrison** [comment]
Hi, and thank you, I can say right away that your desired use case is most certainly possible. Using Asterisk's Audiosocket application to retrieve audio as an input to a STT service is something I used this for myself too, in particular it was IBM's Watson STT and Mozilla's DeepSpeech, both of which worked very well. I unfortunately lost the IBM example, which I would have offered as an example, I do still have the Mozilla DeepSpeech variant. Although that one needs updating and probably of much interest to you since the transcription is performed locally on the device and therefore requires a decent amount of resources. Additionally, its unfortunately not too accurate due to the 8KHz sampled telephone quality audio, which the provided speech model isn't trained on.

Regarding the warning you are receiving, sometimes that can occur while still getting the result you want, but isn't likely, as is your case since Google isn't returning any results to you. I've never used or even looked at Google's STT API before, so at the moment I can't point out what might be causing it, other than generically saying that inbound audio probably isn't being retrieved (fast) enough. If you are okay with sharing your project, I am willing to look over it to see if I can discern where the issue is coming from, and while I haven't used Python in awhile, I could also try to create an example using the Google STT API.

**Comment by c13nt189** [comment]
Thank you for your answer, I am very happy to have your help, initially I want to describe what I have achieved so far in my project with some configurations of my environment, while in a few days I can share my project with you so that you can review it in detail.

First, I share the configuration of my Asterisk 18 Server, which includes the AudioSocket () application, this is the dial plan file in the following path "/etc/asterisk/extensions.conf", where I make the call to the server Streaming started on localhost with port 1121, as shown here:

exten => 112,1,Verbose("Llamada de AudioSocket via Dialplan Application Asterisk")
 same => n,Answer()
 same => n,Set(X-UUID=${CHANNEL:-8}-${STRFTIME(${EPOCH},,%Y-%m%d-%H%M-%s)}00)
 same => n,AudioSocket(${X-UUID},127.0.0.1:1121)
 same => n,Hangup()

On the other hand, based on the documentation I obtained from Google for its STT services at the following link: https://cloud.google.com/speech-to-text/docs/streaming-recognize?hl=en#speech-streaming-mic-recognize-python, I'm trying to combine it with your project "audiosocket_server", so that the input of the audio stream in real time that I get from the call from Asterisk, can be the input of the program Google to use their transcription service, which I reference under the following title in the previous link “Performing streaming speech recognition on an audio stream”, this is the complete description of the script on GitHub https://github.com/googleapis/python-speech/blob/master/samples/microphone/transcribe_streaming_mic.py, I have not yet had success with the combination or integration, since I think I need to understand both programs better, it would be very helpful for me to receive your guide on how achieve the use case mentioned do.

Finally, I am interested in possible you can share your project with me when you used the Mozilla DeepSpech STT engine, I also think it would be a reference to better address the solution of my use case, thank you very much for your help.

**Comment by c13nt189** [comment]
Hello NordHarrison, I wanted to ask you if you have had the opportunity to review the information shared previously, any observation or comment would be very useful to review my project.

On the other hand, I wanted to ask you again to share the script of your project with me when you used the Mozilla DeepSpech STT engine if you see it possible, I think I could get a guide on how to approach the development of my project and solve the barriers that I have at the moment , thank you very much for your help.

**Comment by NormHarrison** [comment]
Hey, I apologize for the delayed reply. I hadn't messed with any of these things in awhile so it took a bit longer than expected to get everything re-setup and become familiar with it again. The original example I mentioned above also used an old version of this project, so I wanted to take the time to re-create it and ensure it worked as expected.

I add the file as an example in the project itself [here](https://github.com/NormHarrison/audiosocket_server/blob/master/examples/example_deepspeech_realtime_transcription.py) with lots of notes explaining what essentially every function call does, although let me know if you still have questions or can't get something to work. The only possible issue that comes to my mind at the moment, is if you use the U-Law audio codec on your server with SIP peers, then you will need to set the `ulaw2lin` keyword argument of the `prepare_output` method to `True`, as the DeepSpeech engine will only accept linear PCM audio.

Again I apologize for the delay, I hope you're able to get results from this example with your own configuration fairly easily.

**Comment by c13nt189** [comment]
Hello NordHarrison, thank you for sharing your insights about what I am trying to achieve, I listened to your recommendations, however, I have still had difficulty getting the Google Cloud services to transcribe the audio in real time that you sent in an Asterisk call Using the AudioSocket Python library that you designed, I would like you to be able to observe my code and if suddenly you can recommend me to re-factor a block that you think is preventing me from achieving it, here is the link: https://github.com/c13nt189/audiosocket-google-stt-realtime/blob/main/demo-stt-google-realtime-audiosocket.py, Any comment you have about this code for me would be well received, since I am not a very experienced programmer, I am attentive to your answers, greetings !.

**Comment by c13nt189** [comment]
Hello @NormHarrison, I hope everything is fine, I would like to write to the private email in order to make a proposal about a bag of support hours, I am still trying to develop the project with the Google Cloud API for the STT without successful results, I will be attentive to you. share your email and I'll explain a little about this.

**Comment by NormHarrison** [comment]
Hi, sorry again for the delay. There's been a few other things I've needed to put my focus towards lately. Someone else has recently opened a similar issue, where they are also trying to use this module in combination with Google's STT service, but seemingly are unable to get back a transcription, as you are. I suspect the issue may be related to the passing of bytes that this module returns, to the `StreamingRecognizeRequest()` method of Google's Python client (although the issue may very well exist elsewhere). Their provided example that uses one's microphone makes use of a bit more complex method that hopefully shouldn't be required in this use case. I plan to try making an example myself in the following days using their service, I will respond as soon as I come to a conclusion on what needs to be done.

Thank you

**Comment by NormHarrison** [comment]
Hi again @c13nt189, I just wanted to let you know that I haven't forgotten about this issue and that I believe I have hopefully come across what needs to be done in order to get it to work correctly with Google's STT service. I plan on being able to post a working example tomorrow. I usually don't make intermittent replies like this, as I like to have the actual example/content ready to posted along with the comment, but in this case since its gone on so long, I felt bad just leaving this issue in silence.

Thank you for your patience.

**Comment by NormHarrison** [comment]
Hi, I want to start off by apologizing for how long this took... more people came across and took interest in this project than I had ever imagined, which I am thrilled about. At the same time though, it had been a few months since the last time I focused on it, including Python as a whole, so unfortunately I had to go through a bit of a process in order to re-engage with it...

As the original reason this issue was opened,  you can now find an [example](https://github.com/NormHarrison/audiosocket_server/blob/master/examples/example_google_stt_realtime_transcription.py) in the examples folder that is specifically for the Google Cloud Platform STT service. The "secret" in getting this module to work with Google's STT client library is by use of generator function. 

Specifically one that looks like this:
```python
def audio_generator():
  while call_conn.connected:
    yield call_conn.read()
```
While the `audio_content` argument of the `StreamingRecognizeRequest` class *does* want a Python bytes instance, the `requests` argument of the `streaming_recognize()` method wants an iterable object (a generator) that produces/returns individual `StreamingRecognizeRequest` instances upon each iteration, with each one containing the next chunk of audio bytes to process.

I made sure that the example linked to above actually produces results before committing it, so I do hope that this can be a candidate for the solution you were looking for. Although please let me know if you encounter any problems.

Thank you

**Comment by c13nt189** [comment]
Hello, I want to apologize for not having written to you before about the project that I am building based on your AudioSocket library, since I was working with another project, I can confirm that the changes made worked correctly, the only thing that adjusted in my project was the code of the language "`language_code = 'es-CO`" and I also omitted the parameter "`model =' phone_call'`", since the latter still does not work in my language, otherwise everything works perfectly, thank you very much for your dedication and commitment in solving this use case, thank you.
