### ISSUE TITLE
Sending audio back to Asterisk

### ISSUE THREAD

**Issue by ivan770** [NormHarrison/audiosocket_server#3]
Hi! I noticed that audio sent back to Asterisk is a bit messy, even if it's just a loopback. But it gets even worse if I try to implement a text-to-speech using [Google Cloud Text-to-Speech](https://cloud.google.com/text-to-speech/docs/reference/rpc/google.cloud.texttospeech.v1) service. Saving response to WAV file and listening it in any audio player gives you a nice audio, while listening to what is sent to Asterisk is *kinda* bad.

I'm not sure if those are issues in my re-implementation (loopback audio gives audio quality just as when using this server) or there are issues in Asterisk config.

**Comment by ivan770** [comment]
GCTTS config is equal to AudioSocket requirements: 8 kHz, mono, 16-bit signed little-endian PCM (checked using WAV spec)

**Comment by NormHarrison** [comment]
Hello @ivan770, I apologize that it's taken me nearly a month to provide you any reply... I'm not sure if this is exactly related to what you were experiencing, but I just came across today a flaw in the `read()` method that returns the bytes of audio from the connected call. I had always assumed that the amount bytes should be the same, and when Audiosocket is sending its expected 16-bit, 8000Hz LE PCM audio, then this seems to be true (this should always be what you receive the the `Audiosocket()` dialplan application is used). However, if Audiosocket is used as a channel driver to `Dial()`, then the sent audio is encoded in whatever codec was agreed upon between Asterisk and bridged channel. I mentioned this in the readme file, but apparently I didn't actually take it into account in the implementation itself... that has been fixed.

As for this module's use in combination with the Google Cloud Platform STT service, [this issue](https://github.com/NormHarrison/audiosocket_server/issues/2) that was opened not long before yours was regarding what I assume to be the exact same problem. [This](https://github.com/NormHarrison/audiosocket_server/issues/2#issuecomment-803259455) post from that issue contains a brief explanation as to what exactly had to be done in order to get it working with Google's client library, and there is now a working example you can find (here)[https://github.com/NormHarrison/audiosocket_server/blob/master/examples/example_google_stt_realtime_transcription.py]. 

Again I apologize for how late this response was, I hope it is able to resolve your issue. If not though please let me know.

Thank you

**Comment by ivan770** [comment]
Thanks!

**Comment by c13nt189** [comment]
Good morning @ivan770 @NormHarrison, do you have an example that you can share to send audio back to AudioSocket, I am generating the audio with the “Google Cloud Text-to-Speech” service, I still can't make it be heard when sending it by the write() method, Thank you so much.

**Comment by ivan770** [comment]
> Good morning @ivan770 @NormHarrison, do you have an example that you can share to send audio back to AudioSocket, I am generating the audio with the “Google Cloud Text-to-Speech” service, I still can't make it be heard when sending it by the write() method, Thank you so much.

Hi! If that helps, whole server for AudioSocket is open-source: https://github.com/ivan770/ems

**Comment by c13nt189** [comment]
Thank you very much @ivan770, I am trying to find an example in Python code, I still do not understand how to return the audio in AudioSocket after generating it with Google's TTS, thanks.

**Comment by bottookku** [comment]
> 

you find possible make it TTS and STT together?

**Comment by bottookku** [comment]
> Большое вам спасибо @ivan770, я пытаюсь найти пример в коде Python, я до сих пор не понимаю, как вернуть звук в AudioSocket после его генерации с помощью TTS Google, спасибо.

you find possible make it TTS and STT together?

**Comment by bottookku** [comment]
> Thank you very much @ivan770, I am trying to find an example in Python code, I still do not understand how to return the audio in AudioSocket after generating it with Google's TTS, thanks.

you find possible make it TTS and STT together?

**Comment by bottookku** [comment]
chunk = 150
  with open('echo123.raw', 'rb') as f:
    data = f.read(chunk)
    while data != b'':
      call_conn.write(data)
      data = f.read(chunk)

what number should be here?
